config/routes.rb
Rails.application.routes.draw do
  root 'volunteers#new'
  resources :volunteers, only: [:new, :create, :update], path: "voluntarios", path_names: {new: "novo"}
  resource :debate_petition_signatures, only: [:new, :create]
  resources :events, only: [:index, :new, :create, :edit, :update], path: "eventos", path_names: {new: "novo", edit: "editar"}

  resources :groups, only: [:show, :new, :create, :edit, :update], path: "nucleos", path_names: {new: "novo", edit: "editar"} do
    collection do
      get :map, path: "mapa"
    end
    resource :group_subscriptions, only: [:create], path: "incricoes"
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  resources :users, only: [:show], path: "usuarios" do
    collection do
      get :search, path: "procurar"
    end

    member do
      put :make_admin, path: "tornar_admin"
    end
  end

  resource :settings, only: [:edit, :update], path: "configuracoes"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :kind, :name, presence: true
  validates :theme, presence: true

  has_many :group_subscriptions

  def territorial?
    self.kind == "territorial"
  end

  def thematic?
    self.kind == "thematic"
  end

  def to_param
    "#{id}-#{self.name.parameterize}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    authorize Group
    @group = Group.find(params[:id].split("-")[0])
    @group_subscription = GroupSubscription.new
  end

  def new
    authorize Group
    @group = Group.new
  end

  def create
    authorize Group
    @group = Group.new(group_params)

    if @group.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    authorize Group
    @group = Group.find(params[:id].split("-")[0])
  end

  def update
    authorize Group

    @group = Group.find(params[:id].split("-")[0])

    if @group.update_attributes(group_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def map
    skip_authorization
  end

  private

  def group_params
    params.require(:group).permit(
      :kind,
      :name,
      :district,
      :address,
      :email,
      :phone,
      :facebook_page,
      :facebook_group,
      :theme,
      :description
    )
  end
end

app/views/groups/_form.erb
<%= form_for @group do |form| %>
  <%= card do %>
    <%= card_header do %>
      <%= @group.persisted? ? "Editar núcleo" : "Novo núcleo" %>
    <% end %>
    <%= card_body do %>
      <div class="mb2">
        <%= form.label :kind_territorial, class: "inline-block label mr2", style: "cursor: pointer" do %>
          <div class="left" style="margin-top: -2px; margin-right: 0.25rem">
            <%= form.radio_button :kind, "territorial" %>
          </div>
          <%= t("activerecord.attributes.group.kind_territorial") %>
        <% end %>

        <%= form.label :kind_thematic, class: "inline-block label", style: "cursor: pointer" do %>
          <div class="left" style="margin-top: -2px; margin-right: 0.25rem">
            <%= form.radio_button :kind, "thematic" %>
          </div>
          <%= t("activerecord.attributes.group.kind_thematic") %>
        <% end %>

        <div class="h6 red kind_errors">
          <%= @group.errors.messages[:kind].join(', ') %>
        </div>
      </div>

      <div class="mb2">
        <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input mb0" %>
        <div class="h6 red name_errors">
          <%= @group.errors.messages[:name].join(', ') %>
        </div>
      </div>

      <div class="mb2">
        <%= form.label :theme, class: "label" %>
        <%= form.select :theme, group_theme_list, {prompt: "Selecione um tema"}, class: "input mb0" %>
        <div class="h6 red theme_errors">
          <%= @group.errors.messages[:theme].join(', ') %>
        </div>
      </div>

      <%= form.label :address, class: "label" %>
      <%= form.text_field :address, class: "input" %>

      <%= form.label :email, class: "label" %>
      <%= form.email_field :email, class: "input" %>

      <%= form.label :phone, class: "label" %>
      <%= form.text_field :phone, class: "input" %>

      <%= form.label :facebook_page, class: "label" %>
      <%= form.url_field :facebook_page, class: "input" %>

      <%= form.label :facebook_group, class: "label" %>
      <%= form.url_field :facebook_group, class: "input" %>

      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "input", style: "box-sizing: border-box; height: 100px" %>
    <% end %>
    <%= card_actions do %>
      <%= form.submit class: "button bg-orange white caps bold p1 border-none h4 rounded" %>
    <% end %>
  <% end %>
<% end %>

app/views/groups/edit.erb
<div class="max-width-2 mx-auto p1">
  <%= render partial: "form" %>
</div>

app/views/groups/map.erb
<% content_for :menu do %>
  <%= link_to "Crie um núcleo", "http://bit.ly/freixo50-novonucleo", class: "block p2 black btn-user-menu" %>
  <%= link_to "Crie o seu evento", "http://bit.ly/freixo50-novoevento", class: "block p2 black btn-user-menu" %>
  <%= link_to "Propostas", "http://bit.ly/freixo50-propostas", class: "block p2 black btn-user-menu" %>
  <%= link_to "Fazer uma doação", "https://eufinancio.marcelofreixo.com.br", class: "block p2 black btn-user-menu" %>
<% end %>

<div style="padding-top: 55px; height: 100%; box-sizing: border-box;">
  <iframe
    src="https://www.google.com/maps/d/embed?mid=1TIyek2ZId4J3BWtp7DiEFt1RkcM"
    frameborder="0"
    style="border:0; width: 100%; height: 100%"
    allowfullscreen>
  </iframe>
</div>

app/views/groups/new.erb
<div class="max-width-2 mx-auto p1">
  <%= render partial: "form" %>
</div>

app/views/groups/show.erb
<%= content_for :head do %>
  <title><%= @group.name %></title>
  <meta property="og:title" content="<%= @group.name %>" />
<% end %>

<div class="bg-cover bg-red clearfix white py3 bg-above" style="margin-top: -55px; padding-top: 80px">
  <div class="max-width-4 mx-auto mxn2 px1">
    <div class="col lg-col-6 px2 mb2">
      <span class="regular h2 m0">
        Bem-vindo ao núcleo
        <span class="bold block"><%= @group.name %></span>
      </span>

      <% if @group.address.present? %>
        <div class="mb1">
          <div class="inline-block center" style="width: 17px">
            <%= icon('map-marker') %>
          </div>
          <%= @group.address %>
        </div>
      <% end %>
      <% if @group.email.present? %>
        <div class="mb1">
          <div class="inline-block center" style="width: 17px">
            <%= icon('envelope-o') %>
          </div>
          <%= @group.email %>
        </div>
      <% end %>
      <% if @group.phone.present? %>
        <div class="mb1">
          <div class="inline-block center" style="width: 17px">
            <%= icon('phone') %>
          </div>
          <%= @group.phone %>
        </div>
      <% end %>

      <% if @group.facebook_page.present? %>
        <div class="mb1">
          <div class="inline-block center" style="width: 17px">
            <%= icon("facebook") %>
          </div>
          <%= link_to("Participe do núcleo no Facebook", @group.facebook_page, target: :blank, class: "white underline") %>
        </div>
      <% end %>

      <% if @group.facebook_group.present? %>
        <div class="mb2">
          <div class="inline-block center" style="width: 17px">
            <%= icon("facebook") %>
          </div>
          <%= link_to("Participe do núcleo no Facebook", @group.facebook_group, target: :blank, class: "white underline") %>
        </div>
      <% end %>

      <% if @group.description.present? %>
        <div class="mb1">
          <%= raw @group.description %>
        </div>
      <% end %>

      <% if policy(Group).edit? %>
        <%=
          link_to(
            "Editar núcleo",
            edit_group_path(@group),
            class: "button bg-aqua white rounded caps bold p1 inline-block mt2"
          )
        %>
      <% end %>
    </div>
    <div class="col lg-col-6 px2">
      <% if flash[:group_subscription_created] %>
        <%= card_body do %>
          <div class="thanks_for_subscribing">
            <p class="mt0">Valeu por se inscrever no nosso núcleo, agora aguarde que entraremos em contato.</p>
            <p>Para fortalecer ainda mais o nosso núcleo, não deixe de compartilhar essa página em suas redes sociais:</p>
            <div class="center">
              <%=
                link_to_popup(
                  "http://www.facebook.com/sharer/sharer.php?u=#{group_url(@group)}",
                  class: "button bg-facebook-blue white caps bold p1 inline-block mb1 rounded"
                ) do
              %>
                <%= icon("facebook") %> Compartilhar
              <% end %>
              <%=
                link_to_popup(
                  "https://twitter.com/intent/tweet?text=#{URI.escape('')}&url=#{group_url(@group)}",
                  class: "button bg-twitter-blue white caps bold p1 inline-block rounded"
                ) do
              %>
                <%= icon("twitter") %> Tweetar
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= form_for [@group, @group_subscription] do |f| %>
          <p class="mt0">Deixe os seus contatos para receber chamados específicos desse núcleo:</p>
          <div class="mb2">
            <%= f.label :email, class: "label" %>
            <%= f.email_field :email, class: "input mb0" %>
            <div class="h6 red email_errors">
              <%= @group_subscription.errors.messages[:email].join(', ') %>
            </div>
          </div>

          <div>
            <%= f.label :phone, class: "label" %>
            <%= f.text_field :phone, class: "input mb0" %>
            <div class="h6 red phone_errors">
              <%= @group_subscription.errors.messages[:phone].join(', ') %>
            </div>
          </div>
          <%= f.submit "Inscrever-se", class: "button bg-aqua p2 caps white border-none h4 rounded bold block mt3", style: "width: 100%" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="max-width-1 mx-auto clearfix px2 py3 center black">
  <h1 class="h3 regular">
    <%= image_tag "volunteers/icone_money.png", class: "mb1", style: "width: 100px" %>
    <h2 class="h1 mt0 caps regular">Faça uma doação</h2>
    <p>
      A sua doação ajuda a gente a estruturar melhor os núcleos da campanha e a garantir que estaremos nos 4 cantos da cidade.
    </p>
  </h1>
  <%=
    link_to(
      "Doar agora",
      "http://eufinancio.marcelofreixo.com.br",
      class: "button bg-orange white px3 py1 caps bold rounded inline-block"
    )
  %>
</div>

<div class="bg-black">
  <div class="max-width-4 mx-auto clearfix center">
    <%= link_to "Crie um núcleo", "http://bit.ly/freixo50-novonucleo", class: "button p2 white inline-block" %>
    <%= link_to "Crie o seu evento", "http://bit.ly/freixo50-novoevento", class: "button p2 white inline-block" %>
    <%= link_to "Propostas", "http://bit.ly/freixo50-propostas", class: "button p2 white inline-block" %>
    <%= link_to "Fazer uma doação", "https://eufinancio.marcelofreixo.com.br", class: "button p2 white inline-block" %>
  </div>
</div>