config/routes.rb
Rails.application.routes.draw do
  root 'volunteers#new'
  resources :volunteers, only: [:new, :create, :update], path: "voluntarios", path_names: {new: "novo"}
  resource :debate_petition_signatures, only: [:new, :create]
  resources :events, only: [:index, :new, :create, :edit, :update], path: "eventos", path_names: {new: "novo", edit: "editar"}

  resources :groups, only: [:show, :new, :create, :edit, :update], path: "nucleos", path_names: {new: "novo", edit: "editar"} do
    collection do
      get :map, path: "mapa"
    end
    resource :group_subscriptions, only: [:create], path: "incricoes"
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  resources :users, only: [:show], path: "usuarios" do
    collection do
      get :search, path: "procurar"
    end

    member do
      put :make_admin, path: "tornar_admin"
    end
  end

  resource :settings, only: [:edit, :update], path: "configuracoes"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_card.erb
<div class="bg-white rounded mb2 <%= options[:class] %>" style="box-shadow: 0 0 2px #999">
  <%= yield %>
</div>

app/views/shared/_card_actions.erb
<div class="p1 border-top border-silver">
  <%= yield %>
</div>

app/views/shared/_card_body.erb
<div class="p2">
  <%= yield %>
</div>

app/views/shared/_card_header.erb
<div class="p2 h3">
  <%= yield %>
</div>

app/views/shared/_dialog.erb
<script>
  closeDialog<%= id %> = function () {
    var dialog = document.getElementById("<%= id %>")
    dialog.className = dialog.className.concat([" hide"])
    return false
  }
</script>

<div
  id="<%= id %>"
  onClick="return closeDialog<%= id %>()"
  class="fixed bg-darken-4 flex center items-center justify-center hide"
  style="top: 0; left: 0; width: 100vw; height: 100vh; z-index: 10000">
  <div
    class="inline-block"
    style="max-width: 100%; overflow-y: scroll; overflow-x: hidden; max-height: 90vh; position: relative">
    <%= yield %>
    <a
      href="#"
      onClick="return closeDialog<%= id %>()"
      class="black p1"
      style="position: absolute; top: 0; right: 0;">
      <%= icon('times') %>
    </a>
  </div>
</div>

app/views/shared/_flash.erb
<div class="clearfix mt2">
  <div class="col col-12 px2 center">
    <div
      id="<%= type %>-message"
      class="px2 py1 bg-<%= type == :notice ? "green" : "red" %> white rounded inline-block">
      <%= message %>
    </div>
  </div>
</div>

app/views/shared/_link_to_popup.erb
<script>
  openPopup = function (path, text) {
    window.open(path, text, 'height=600,width=710')
    return false
  }
</script>

<%= link_to(path, options.merge(onClick: "return openPopup('#{path}')")) do %>
  <%= capture(&block) %>
<% end %>

app/views/shared/_signup_form.erb
<%= card do %>
  <%= card_header do %>
    Crie sua conta
  <% end %>
  <%= card_body do %>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <div class="mxn2">
        <div class="col col-12 md-col-6 px2 mb3">
          <%= f.label :first_name, class: "label required" %>
          <%= f.text_field :first_name, autofocus: true, class: "input", style: "margin-bottom: .25rem" %>
          <div class="h6 red first_name_errors">
            <%= resource.errors.messages[:first_name].join(', ') %>
          </div>
        </div>

        <div class="col col-12 md-col-6 px2 mb3">
          <%= f.label :last_name, class: "label required" %>
          <%= f.text_field :last_name, class: "input", style: "margin-bottom: .25rem" %>
          <div class="h6 red last_name_errors">
            <%= resource.errors.messages[:last_name].join(', ') %>
          </div>
        </div>
      </div>

      <div class="mb3">
        <%= f.label :email, class: "label required" %>
        <%= f.email_field :email, class: "input", style: "margin-bottom: .25rem" %>
        <div class="h6 red email_errors">
          <%= resource.errors.messages[:email].join(', ') %>
        </div>
      </div>

      <div class="mb3">
        <%= f.label :district, class: "label" %>
        <%= f.text_field :district, class: "input", style: "margin-bottom: .25rem" %>
        <div class="h6 red"><%= resource.errors.messages[:district].join(', ') %></div>
      </div>

      <div class="mb3">
        <%= f.label :cell_phone_number, class: "label" %>
        <%= f.telephone_field :cell_phone_number, class: "input", style: "margin-bottom: .25rem" %>
        <div class="h6 red"><%= resource.errors.messages[:cell_phone_number].join(', ') %></div>
      </div>

      <div class="clearfix mxn2">
        <div class="mb3 col col-12 md-col-6 px2">
          <%= f.label :password, class: "label required" %>
          <%= f.password_field :password, autocomplete: "off", class: "input", style: "margin-bottom: .25rem" %>
          <div class="h6 red password_errors">
            <%= resource.errors.messages[:password].join(', ') %>
          </div>
        </div>

        <div class="mb3 col col-12 md-col-6 px2">
          <%= f.label :password_confirmation, class: "label required" %>
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "input", style: "margin-bottom: .25rem" %>
          <div class="h6 red"><%= resource.errors.messages[:password_confirmation].join(', ') %></div>
        </div>
      </div>

      <div>
        <%= f.submit "Cadastrar", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_toggle_link_to.erb
<script>
  toggle<%= id %> = function () {
    var toggable = document.getElementById("<%= id %>")

    if (toggable.className.includes("hide")) {
      toggable.className = toggable.className.replace("hide", "")
    } else {
      toggable.className = toggable.className.concat([" hide"])
    }

    return false
  }
</script>

<%= link_to "##{id}", options.merge({onClick: "return toggle#{id}()"}) do %>
  <%= yield %>
<% end %>

app/views/shared/_user_menu.erb
<script>
  toggleUserMenu = function () {
    var userMenu = document.getElementById("user-menu")
    var overlay = document.getElementById("user-menu-overlay")

    if (userMenu.className.includes("hide")) {
      userMenu.className = userMenu.className.replace("hide", "")
      overlay.className = overlay.className.replace("hide", "")
    } else {
      userMenu.className = userMenu.className.concat([" hide"])
      overlay.className = overlay.className.concat([" hide"])
    }

    return false
  }
</script>

<style>
  .btn-user-menu:hover {
    background: #eee;
  }
</style>

<div
  id="user-menu-overlay"
  class="hide"
  onClick="return toggleUserMenu()"
  style="position: absolute; width: 100vw; height: 100vh; top: 0; left: 0">
</div>

<div class="left relative">
  <%= link_to "#", class: "h1", onClick: "return toggleUserMenu()" do %>
    <%= icon "bars", class: "aqua" %>
  <% end %>

  <div
    id="user-menu"
    class="bg-white black absolute left-0 rounded hide"
    style="white-space: nowrap; box-shadow: 0 0 2px #999; top: 45px;">

    <%= yield :menu %>

    <% if current_user.present? %>
      <div class="p2 flex items-center">
        <%= avatar user.image, class: "mr1" %>
        <div>
          <div class="bold"><%= user.first_name %> <%= user.last_name %></div>
          <div><%= user.email %></div>
        </div>
      </div>
      <%= link_to "Editar perfil", edit_user_registration_path, class: "block p2 black btn-user-menu" %>
      <%= link_to "Procurar usuário", search_users_path, class: "block p2 black btn-user-menu" %>
      <%= link_to "Eventos", events_path, class: "block p2 black btn-user-menu" %>

      <% if policy(Group).create? %>
        <%= link_to "Criar núcleo", new_group_path, class: "block p2 black btn-user-menu" %>
      <% end %>

      <% if policy(Setting).edit? %>
        <%= link_to "Configurações do site", edit_settings_path, class: "block p2 black btn-user-menu" %>
      <% end %>

      <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "block p2 black btn-user-menu" %>
    <% end %>
  </div>
</div>