config/routes.rb
Rails.application.routes.draw do
  root 'volunteers#new'
  resources :volunteers, only: [:new, :create, :update], path: "voluntarios", path_names: {new: "novo"}
  resource :debate_petition_signatures, only: [:new, :create]
  resources :events, only: [:index, :new, :create, :edit, :update], path: "eventos", path_names: {new: "novo", edit: "editar"}

  resources :groups, only: [:show, :new, :create, :edit, :update], path: "nucleos", path_names: {new: "novo", edit: "editar"} do
    collection do
      get :map, path: "mapa"
    end
    resource :group_subscriptions, only: [:create], path: "incricoes"
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  resources :users, only: [:show], path: "usuarios" do
    collection do
      get :search, path: "procurar"
    end

    member do
      put :make_admin, path: "tornar_admin"
    end
  end

  resource :settings, only: [:edit, :update], path: "configuracoes"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organizer, class_name: "User"
  validates :title, :start_at, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    skip_authorization
    @events = Event.order(start_at: "desc")
  end

  def new
    authorize Event
    @event = Event.new
  end

  def create
    authorize Event

    @event = Event.new(event_params)
    @event.organizer = User.find_by(email: params[:organizer_email])

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    authorize Event
    @event = Event.find(params[:id])
  end

  def update
    authorize Event
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to events_path, notice: "Evento atualizado!"
    else
      render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :title,
      :category,
      :short_description,
      :long_description,
      :address,
      :start_at,
      :facebook_link,
      :google_calendar_link,
      :has_streaming
    )
  end
end

app/views/events/_form.erb
<%= form_for @event do |form| %>
  <%= card do %>
    <%= card_body do %>
      <div class="mb3">
        <%= label_tag :organizer_email, "Email do organizador", class: "label" %>
        <%= email_field_tag :organizer_email, nil, class: "input" %>
      </div>

      <div class="mb3">
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, class: "input", style: "margin-bottom: .25rem" %>
        <div class="h6 red title_errors">
          <%= @event.errors.messages[:title].join(', ') %>
        </div>
      </div>

      <div class="mb3">
        <%= form.label :category, class: "label" %>
        <%= form.select :category, event_category_list, {}, class: "input rounded" %>
      </div>

      <div class="mb3">
        <%= form.label :short_description, class: "label" %>
        <%= form.text_area :short_description, class: "input", style: "box-sizing: border-box" %>
      </div>

      <div class="mb3">
        <%= form.label :long_description, class: "label" %>
        <%= form.text_area :long_description, class: "input", style: "box-sizing: border-box" %>
      </div>

      <div class="mb3">
        <%= form.label :address, class: "label" %>
        <%= form.text_field :address, class: "input" %>
      </div>

      <div class="mb3">
        <%= form.label :start_at, class: "label" %>
        <%= form.datetime_select :start_at, {}, class: "input", style: "display: inline-block; width: auto" %>
      </div>

      <div class="mb3">
        <%= form.label :facebook_link, class: "label" %>
        <%= form.url_field :facebook_link, class: "input" %>
      </div>

      <div class="mb3">
        <%= form.label :google_calendar_link, class: "label" %>
        <%= form.url_field :google_calendar_link, class: "input" %>
      </div>

      <div>
        <%= form.label :has_streaming, class: "label" do %>
          <%= form.check_box :has_streaming %>
          <%= t('activerecord.attributes.event.has_streaming') %>
        <% end %>
      </div>
    <% end %>
    <%= card_actions do %>
      <%= form.submit nil, class: "button px2 py1 bg-orange white bold border-none caps h4" %>
      <%= link_to "Cancelar", :back, class: "button px2 py1 bg-gray white bold border-none caps h4" %>
    <% end %>
  <% end %>
<% end %>

app/views/events/edit.erb
<div class="max-width-2 mx-auto">
  <div class="px2 mt2">
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/index.erb
<div class="p2 max-width-2 mx-auto">
  <div class="clearfix mb3">
    <h1 class="regular left m0">Eventos</h1>
    <%= link_to "Novo evento", new_event_path, class: "button bold caps bg-orange px2 py1 white border-none inline-block rounded right" %>
  </div>

  <% @events.each do |event| %>
    <%= card do %>
      <%= card_header do %>
        <div>
          <%= event.title %>
        </div>
        <div class="h5">
          <%= l(event.start_at, format: :short) %>
        </div>
      <% end %>
      <%= card_actions do %>
        <%= link_to "Editar", edit_event_path(event), class: "button bg-white orange caps bold p1 h6 inline-block" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/events/new.erb
<div class="max-width-2 mx-auto">
  <div class="px2 mt2">
    <%= form_for @event do |form| %>
      <%= card do %>
        <%= card_header do %>
          Novo evento
        <% end %>
        <%= card_body do %>
          <div class="mb3">
            <%= label_tag :organizer_email, "Email do organizador", class: "label" %>
            <%= email_field_tag :organizer_email, nil, class: "input" %>
          </div>

          <div class="mb3">
            <%= form.label :title, class: "label" %>
            <%= form.text_field :title, class: "input", style: "margin-bottom: .25rem" %>
            <div class="h6 red title_errors">
              <%= @event.errors.messages[:title].join(', ') %>
            </div>
          </div>

          <div class="mb3">
            <%= form.label :category, class: "label" %>
            <%= form.select :category, event_category_list, {}, class: "input rounded" %>
          </div>

          <div class="mb3">
            <%= form.label :short_description, class: "label" %>
            <%= form.text_area :short_description, class: "input", style: "box-sizing: border-box" %>
          </div>

          <div class="mb3">
            <%= form.label :long_description, class: "label" %>
            <%= form.text_area :long_description, class: "input", style: "box-sizing: border-box" %>
          </div>

          <div class="mb3">
            <%= form.label :address, class: "label" %>
            <%= form.text_field :address, class: "input" %>
          </div>

          <div class="mb3">
            <%= form.label :start_at, class: "label" %>
            <%= form.datetime_select :start_at, {}, class: "input", style: "display: inline-block; width: auto" %>
          </div>

          <div class="mb3">
            <%= form.label :facebook_link, class: "label" %>
            <%= form.url_field :facebook_link, class: "input" %>
          </div>

          <div class="mb3">
            <%= form.label :google_calendar_link, class: "label" %>
            <%= form.url_field :google_calendar_link, class: "input" %>
          </div>

          <div>
            <%= form.label :has_streaming, class: "label" do %>
              <%= form.check_box :has_streaming %>
              <%= t('activerecord.attributes.event.has_streaming') %>
            <% end %>
          </div>
        <% end %>
        <%= card_actions do %>
          <%= form.submit "Criar evento", class: "button px2 py1 bg-orange white bold border-none caps h4" %>
          <%= link_to "Cancelar", :back, class: "button px2 py1 bg-gray white bold border-none caps h4" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>