config/routes.rb
Rails.application.routes.draw do
  root 'volunteers#new'
  resources :volunteers, only: [:new, :create, :update], path: "voluntarios", path_names: {new: "novo"}
  resource :debate_petition_signatures, only: [:new, :create]
  resources :events, only: [:index, :new, :create, :edit, :update], path: "eventos", path_names: {new: "novo", edit: "editar"}

  resources :groups, only: [:show, :new, :create, :edit, :update], path: "nucleos", path_names: {new: "novo", edit: "editar"} do
    collection do
      get :map, path: "mapa"
    end
    resource :group_subscriptions, only: [:create], path: "incricoes"
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  resources :users, only: [:show], path: "usuarios" do
    collection do
      get :search, path: "procurar"
    end

    member do
      put :make_admin, path: "tornar_admin"
    end
  end

  resource :settings, only: [:edit, :update], path: "configuracoes"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")
  namespace Rails.env
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    authorize Setting
  end

  def update
    authorize Setting
    Setting.livestream_embed = params[:livestream_embed]
    Setting.daily_task_description = params[:daily_task_description]
    Setting.daily_task_link = params[:daily_task_link]
    redirect_to edit_settings_path, notice: "Suas alterações foram salvas com sucesso"
  end
end

app/views/settings/edit.erb
<div class="max-width-1 mx-auto px1 py1">
  <%= form_tag settings_path, method: :put do %>
    <%= card do %>
      <%= card_body do %>

        <%= label_tag :livestream_embed, "Embed da transmissão ao vivo", class: "label" %>
        <small>Deixe o campo abaixo em branco para desativar a transmissão ao vivo</small>
        <%=
          text_area_tag(
            :livestream_embed,
            Setting.livestream_embed,
            class: "input mt1",
            style: "box-sizing: border-box; height: 150px"
          )
        %>

        <%= label_tag :daily_task_description, "Descrição da tarefa do dia", class: "label" %>
        <small>Deixe o campo abaixo em branco para desativar a tarefa do dia</small>
        <%=
          text_area_tag(
            :daily_task_description,
            Setting.daily_task_description,
            class: "input mt1",
            style: "box-sizing: border-box; height: 75px"
          )
        %>

        <%= label_tag :daily_task_link, "Link da tarefa do dia", class: "label" %>
        <%=
          text_field_tag(
            :daily_task_link,
            Setting.daily_task_link,
            class: "input mb0"
          )
        %>
      <% end %>
      <%= card_actions do %>
        <%= submit_tag "Salvar", class: "button orange bg-white px2 py1 border-none caps bold" %>
      <% end %>
    <% end %>
  <% end %>
</div>